name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - run: echo "{ \"hello\": \"there\" }" > config.json

    - run: mkdir -p build/release

    - run: dotnet publish -c Release -r ubuntu.16.04-x64 -o ./build/release/

    - uses: actions/upload-artifact@master
      with:
        name: build-artifacts
        path: build/release
