name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build on Ubuntu 16.04
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    
    - name: Make dummy config
      run: echo { } > config.json
    
    - name: Create build directory
      run: mkdir -p build/release
    
    - name: Build
      run: dotnet publish -c Release -r ubuntu.16.04-x64 -o ./build/release/ /p:PublishSingleFile=true /p:PublishTrimmed=true /p:DebugType=None
    
    - uses: actions/upload-artifact@master
      with:
        name: build-artifacts
        path: build/release
