name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build on Ubuntu 16.04
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    
    - name: Make dummy config
      run: echo "{ \"hello\": \"there\" }" > config.json
    
    - name: Create build directory
      run: mkdir -p build/release
    
    - name: Build
      run: dotnet publish -c Release -r ubuntu.16.04-x64 -o ./build/release/
    
    - uses: actions/upload-artifact@master
      with:
        name: build-artifacts
        path: build/release
